USE COMPANY;
-- view all employees
SELECT * FROM EMPLOYEES;

-- view all departments
SELECT * FROM DEPARTMENTS;

-- employees with salary greater than 50000
SELECT EMPLOYEE_ID,EMPLOYEE_NAME,SALARY FROM EMPLOYEES WHERE SALARY > 50000;

--employees age between 25 and 30
SELECT EMPLOYEE_ID,EMPLOYEE_NAME,AGE FROM EMPLOYEES WHERE AGE BETWEEN 25 AND 30;

--top 5 highest paid employees
SELECT EMPLOYEE_ID,EMPLOYEE_NAME,SALARY AS HIGHEST_SALARY FROM EMPLOYEES ORDER BY SALARY DESC LIMIT 5;

--sort employee by salary
SELECT * FROM EMPLOYEES ORDER BY SALARY DESC;

--count employees
SELECT COUNT(*) AS TOTAL_EMPLOYEES FROM EMPLOYEES;

--average salary
SELECT AVG(SALARY) FROM EMPLOYEES;

--maximum salary 
SELECT MAX(SALARY) FROM EMPLOYEES;

--minimum salary
SELECT MIN(SALARY) FROM EMPLOYEES;

--total salary paid to employees
SELECT SUM(SALARY) FROM EMPLOYEES;

--employee with department details
SELECT E.EMPLOYEE_ID,E.EMPLOYEE_NAME,D.DEPARTMENT_NAME FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

--employee in IT Department
SELECT E.EMPLOYEE_ID,E.EMPLOYEE_NAME,D.DEPARTMENT_NAME FROM EMPLOYEES E 
INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID WHERE D.DEPARTMENT_NAME = 'IT';

--number of employees in each department 
SELECT COUNT(*) AS NUMBER_OF_EMPLOYEES,D.DEPARTMENT_NAME FROM EMPLOYEES E INNER JOIN DEPARTMENTS D
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME;

--average salary by department 
SELECT AVG(SALARY) AS AVG_SALARY,D.DEPARTMENT_NAME FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D ON D.DEPARTMENT_ID = E.DEPARTMENT_ID 
GROUP BY D.DEPARTMENT_NAME ORDER BY AVG_SALARY DESC; 

--highest salary by department
SELECT MAX(SALARY) AS HIGHEST_SALARY,D.DEPARTMENT_NAME FROM EMPLOYEES E 
INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID GROUP BY D.DEPARTMENT_NAME ORDER BY HIGHEST_SALARY DESC;

--second highest salary (using subqueries)
SELECT MAX(SALARY) FROM EMPLOYEES
WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEES);